[package]
name = "input_classifier"
authors = ["Warp Team <dev@warp.dev>"]
edition = "2024"
publish.workspace = true
license.workspace = true

[features]
# Selects which shell-command heuristic behavior is used. If both are enabled, v2 wins.
nld_heuristic_v1 = []
nld_heuristic_v2 = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
itertools.workspace = true
futures-lite.workspace = true
lazy_static.workspace = true
log.workspace = true
natural_language_detection.workspace = true
serde.workspace = true
smol_str.workspace = true
warp_completer.workspace = true

[dev-dependencies]
warp_features.workspace = true
